apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-lab
spec:
  version: 8.8.1
  count: 3
  elasticsearchRef:
    name: "elasticsearch-lab"
    namespace: elastic-system
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
