apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
spec:
  selector:
    app: kibana-sample-kb-http
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: LoadBalancer
