apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/elasticsearch-local-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1
