apiVersion: v1
kind: Service
metadata:
  name: legollyweb-loadbalancer
  namespace: legolly
spec:
  selector:
    app: legollyweb
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
