apiVersion: v1
kind: Deployment
metadata:
  name: legollyweb
spec:
   replicas: 2
   selector:
     matchLabels:
       app: legollyweb
   template:
     metadata:
       labels:
         app: legollyweb
     spec:
       containers:
       - name: legollyweb-container
         image: ajpahl1008/legollyweb-x86:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 3000
           name: legollyweb
             #         imagePullSecrets:
             #- name: regcred
